# Site settings
title: 蒋贤斌的博客
description: '这里应有一句励志的格言'
url: 'http://bing0say.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'bingosay'
  email: bingoosay@gmail.com
  twitter_username: Hibingosay
  facebook_username: bingosay
  github_username:  bing0say
  linkedin_username:  bingosay

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
